modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/MachaCeleste/ToHellWithYou/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/MachaCeleste/ToHellWithYou"
logoFile="pack.png"
credits="Art: PequiSoda https://bsky.app/profile/pequisoda.bsky.social"
authors="${mod_authors}"
description='''${mod_description}'''